print("----------------------------------------------------------------------------")
print("cool message")
print("yes i did add some cool lua scripting to print these messages")
print("this is so cool")
print("should i add a button that prints to the console of napture?")
print("i might make it so you can print what you typed in napture logs")
print("this is so cool tho")
print("-chill.web creator")
